version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ascopes"
    labels:
      - "ci"
      - "tiny"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ascopes"
    labels:
      - "maven"
      - "tiny"
