name: Deploy a branch

on:
  workflow_dispatch:
    inputs:
      deploy-javadoc-to-gh-pages:
        description: "Should I deploy JavaDocs to GitHub pages?"
        required: true
        type: boolean

jobs:
  github:
    name: "Deploy to GitHub"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          # Must use >= JDK 17 for Javadocs to generate correctly.
          java-version: 17

      - name: Build artifacts and deploy to GitHub packages.
        run: >-
          ./mvnw
          -B
          -T4C
          --no-transfer-progress
          -Dmaven.source.includePom=true
          -Dstyle.color=always
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          clean install javadoc:jar source:jar deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload JavaDocs as a build artifact
        if: ${{ inputs.deploy-javadoc-to-gh-pages }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: java-compiler-testing/target/apidocs

      - name: Deploy JavaDocs build artifact to GitHub Pages
        if: ${{ inputs.deploy-javadoc-to-gh-pages }}
        id: deployment
        uses: actions/deploy-pages@v1
