# This is kept separate to the PR pipeline, despite being identical.
# The separation is used to allow creation of a status badge for the main branch
# which is included in the README without reflecting PR statuses in that metric.

name: Main branch build
on:
  push:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/_run-tests.yml
  javadocs:
    name: JavaDocs
    uses: ./.github/workflows/_generate-javadocs.yml
  compliance:
    name: Compliance
    uses: ./.github/workflows/_check-compliance.yml
